export const dispensaries = [
  {
    id: 1,
    name: "Green Harbor Collective",
    city: "Denver, CO",
    distance: "0.8 mi",
    rating: 4.9,
    type: "Rec + Med",
    hours: "8AM–10PM",
    deals: 12,
    specialty: "Craft Flower",
    zip: "80202",
  },
  {
    id: 2,
    name: "Silver Sage Apothecary",
    city: "Portland, OR",
    distance: "1.2 mi",
    rating: 4.8,
    type: "Recreational",
    hours: "9AM–9PM",
    deals: 7,
    specialty: "Concentrates",
    zip: "97201",
  },
  {
    id: 3,
    name: "The Ember Room",
    city: "Los Angeles, CA",
    distance: "2.1 mi",
    rating: 4.7,
    type: "Rec + Med",
    hours: "7AM–11PM",
    deals: 18,
    specialty: "Edibles",
    zip: "90028",
  },
  {
    id: 4,
    name: "North Star Cannabis",
    city: "Seattle, WA",
    distance: "3.4 mi",
    rating: 4.9,
    type: "Recreational",
    hours: "8AM–12AM",
    deals: 9,
    specialty: "Live Rosin",
    zip: "98101",
  },
  {
    id: 5,
    name: "Desert Bloom Dispensary",
    city: "Phoenix, AZ",
    distance: "4.0 mi",
    rating: 4.6,
    type: "Medical",
    hours: "9AM–8PM",
    deals: 5,
    specialty: "Tinctures",
    zip: "85004",
  },
  {
    id: 6,
    name: "Harvest Moon Co.",
    city: "Boston, MA",
    distance: "5.2 mi",
    rating: 4.8,
    type: "Rec + Med",
    hours: "10AM–10PM",
    deals: 14,
    specialty: "Pre-rolls",
    zip: "02108",
  },
];

export const strains = [
  {
    name: "Blue Dream",
    type: "Hybrid",
    thc: "24%",
    cbd: "0.8%",
    effects: ["Euphoric", "Creative", "Relaxed"],
    price: "$45/3.5g",
    rating: 4.9,
  },
  {
    name: "Wedding Cake",
    type: "Indica",
    thc: "27%",
    cbd: "0.4%",
    effects: ["Relaxed", "Happy", "Sleepy"],
    price: "$55/3.5g",
    rating: 4.8,
  },
  {
    name: "Sour Diesel",
    type: "Sativa",
    thc: "22%",
    cbd: "0.5%",
    effects: ["Energetic", "Focused", "Uplifted"],
    price: "$42/3.5g",
    rating: 4.7,
  },
  {
    name: "Gelato #33",
    type: "Hybrid",
    thc: "25%",
    cbd: "0.6%",
    effects: ["Euphoric", "Giggly", "Creative"],
    price: "$60/3.5g",
    rating: 4.9,
  },
  {
    name: "Northern Lights",
    type: "Indica",
    thc: "21%",
    cbd: "1.2%",
    effects: ["Sleepy", "Hungry", "Relaxed"],
    price: "$40/3.5g",
    rating: 4.6,
  },
  {
    name: "Jack Herer",
    type: "Sativa",
    thc: "23%",
    cbd: "0.7%",
    effects: ["Happy", "Energetic", "Focused"],
    price: "$48/3.5g",
    rating: 4.8,
  },
];

export const states = [
  {
    name: "Colorado",
    status: "Rec + Med",
    since: 2014,
    age: 21,
    possession: "2 oz",
    tax: "15% + 2.9%",
    code: "CO",
  },
  {
    name: "California",
    status: "Rec + Med",
    since: 2016,
    age: 21,
    possession: "1 oz",
    tax: "15% + 7.25%",
    code: "CA",
  },
  {
    name: "Oregon",
    status: "Rec + Med",
    since: 2014,
    age: 21,
    possession: "1 oz",
    tax: "17%",
    code: "OR",
  },
  {
    name: "Washington",
    status: "Rec + Med",
    since: 2012,
    age: 21,
    possession: "1 oz",
    tax: "37%",
    code: "WA",
  },
  {
    name: "New York",
    status: "Rec + Med",
    since: 2021,
    age: 21,
    possession: "3 oz",
    tax: "13%",
    code: "NY",
  },
  {
    name: "Illinois",
    status: "Rec + Med",
    since: 2020,
    age: 21,
    possession: "1 oz",
    tax: "10–25%",
    code: "IL",
  },
  {
    name: "Massachusetts",
    status: "Rec + Med",
    since: 2016,
    age: 21,
    possession: "1 oz",
    tax: "17%",
    code: "MA",
  },
  {
    name: "Arizona",
    status: "Rec + Med",
    since: 2020,
    age: 21,
    possession: "1 oz",
    tax: "16%",
    code: "AZ",
  },
  {
    name: "Florida",
    status: "Medical",
    since: 2016,
    age: 18,
    possession: "Varies",
    tax: "None",
    code: "FL",
  },
  {
    name: "Texas",
    status: "Limited Med",
    since: 2015,
    age: 18,
    possession: "Low THC",
    tax: "None",
    code: "TX",
  },
];

export const menu = [
  {
    name: "Gelato Live Rosin",
    category: "Concentrate",
    thc: "78%",
    price: 65,
    size: "1g",
    vendor: "710 Labs",
    stock: "Low",
  },
  {
    name: "Blue Dream Flower",
    category: "Flower",
    thc: "24%",
    price: 45,
    size: "3.5g",
    vendor: "Cookies",
    stock: "In",
  },
  {
    name: "Watermelon Gummies",
    category: "Edible",
    thc: "100mg",
    price: 25,
    size: "10pk",
    vendor: "Wyld",
    stock: "In",
  },
  {
    name: "Pax Era Pod — Sunset",
    category: "Vape",
    thc: "85%",
    price: 55,
    size: "0.5g",
    vendor: "Pax",
    stock: "In",
  },
  {
    name: "OG Kush Pre-roll 5pk",
    category: "Pre-roll",
    thc: "22%",
    price: 35,
    size: "0.5g ea",
    vendor: "Jeeter",
    stock: "Low",
  },
  {
    name: "CBD Relief Tincture",
    category: "Tincture",
    thc: "2:1",
    price: 48,
    size: "30ml",
    vendor: "Papa & Barkley",
    stock: "In",
  },
  {
    name: "Wedding Cake Shatter",
    category: "Concentrate",
    thc: "82%",
    price: 40,
    size: "1g",
    vendor: "Raw Garden",
    stock: "Out",
  },
  {
    name: "Sour Diesel Cart",
    category: "Vape",
    thc: "88%",
    price: 50,
    size: "1g",
    vendor: "Stiiizy",
    stock: "In",
  },
];
